

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    user: django-user
    environment:
      - DB_HOST=db
      - DB_NAME=delaquash
      - DB_USER=delaquash
      - DB_PASS=delaquash
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=delaquash
      - POSTGRES_USER=delaquash
      - POSTGRES_PASSWORD=delaquash
    
volumes:
  dev-db-data: